// Generated by IcedCoffeeScript 108.0.7
(function() {
  var Config, iced, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  exports.Config = Config = (function() {
    function Config(_arg) {
      this.reqeng = _arg.reqeng, this.C = _arg.C, this.fq_api_endpoint = _arg.fq_api_endpoint, this.escape_user_content = _arg.escape_user_content;
    }

    Config.prototype.request = function(args, cb) {
      var err, res, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      if ((args.endpoint != null) && (this.fq_api_endpoint != null)) {
        args.url = this.fq_api_endpoint(args.endpoint);
      }
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/libweb/src/base/config.iced",
            funcname: "Config.request"
          });
          _this.reqeng.request(args, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return res = arguments[1];
              };
            })(),
            lineno: 23
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          if ((typeof err !== "undefined" && err !== null) && (_this.escape_user_content != null)) {
            err = new Error(_this.escape_user_content(err.message));
          }
          return cb(err, res);
        };
      })(this));
    };

    return Config;

  })();

}).call(this);
