// Generated by IcedCoffeeScript 108.0.7
(function() {
  var Config, EUI, Request;

  EUI = function() {
    return new Error("Unimplemented");
  };

  exports.Request = Request = (function() {
    function Request(_arg) {
      this.get_csrf_token = _arg.get_csrf_token;
    }

    Request.prototype.request = function(args, cb) {
      return cb(EUI());
    };

    return Request;

  })();

  exports.Config = Config = (function() {
    function Config(_arg) {
      this.request = _arg.request;
    }

    return Config;

  })();

}).call(this);
