// Generated by IcedCoffeeScript 108.0.7
(function() {
  var Config, Request;

  exports.Request = Request = (function() {
    function Request(_arg) {
      this.impl = _arg.impl, this.get_csrf_token = _arg.get_csrf_token;
    }

    return Request;

  })();

  exports.Config = Config = (function() {
    function Config(_arg) {
      this.request = _arg.request;
    }

    return Config;

  })();

}).call(this);
