// Generated by IcedCoffeeScript 108.0.7
(function() {
  var EUI, Request,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  EUI = function() {
    return new Error("Unimplemented");
  };

  exports.Request = Request = (function() {
    function Request(_arg) {
      this.get_csrf_token = _arg.get_csrf_token;
    }

    Request.prototype.request = function(args, cb) {
      return cb(EUI());
    };

    Request.prototype._make_headers = function(_arg) {
      var headers, method, t;
      headers = _arg.headers, method = _arg.method;
      headers || (headers = {});
      if (method === "POST" && ((t = typeof this.get_csrf_token === "function" ? this.get_csrf_token() : void 0) != null) && t.length) {
        headers["X-CSRF-Token"] = t;
      }
      return headers;
    };

    Request.prototype._handle_response = function(_arg, cb) {
      var body, d, err, http_status, inargs, json_status, method, msg, ok_empty_body, ok_http_status_codes, ok_json_status_codes, url, _ref, _ref1;
      err = _arg.err, inargs = _arg.inargs, body = _arg.body, http_status = _arg.http_status;
      url = inargs.url, method = inargs.method, ok_http_status_codes = inargs.ok_http_status_codes, ok_json_status_codes = inargs.ok_json_status_codes, ok_empty_body = inargs.ok_empty_body;
      ok_http_status_codes || (ok_http_status_codes = [200]);
      ok_json_status_codes || (ok_json_status_codes = ['OK']);
      err = null;
      json_status = null;
      if ((http_status != null) && !(__indexOf.call(ok_http_status_codes, http_status) >= 0)) {
        msg = "error in " + method;
        if (http_status != null) {
          msg += " (HTTP code " + http_status + ")";
        }
        err = new Error(msg);
      } else if (err != null) {

      } else if (body == null) {
        if (!ok_empty_body) {
          err = new Error("empty body sent back from server");
        }
      } else if (((json_status = (_ref = body.status) != null ? _ref.name : void 0) == null) || !(__indexOf.call(ok_json_status_codes, json_status) >= 0)) {
        msg = "Server failure";
        if ((d = body != null ? (_ref1 = body.status) != null ? _ref1.desc : void 0 : void 0)) {
          msg += ": " + d;
        }
        err = new Error(msg);
      }
      return cb(err, {
        body: body,
        json_status: json_status,
        http_status: http_status
      });
    };

    return Request;

  })();

}).call(this);
