// Generated by IcedCoffeeScript 108.0.7
(function() {
  var xor_buffers,
    __slice = [].slice;

  exports.xor_buffers = xor_buffers = function() {
    var b, buffers, c, err, i, j, l, res, _i, _j, _len, _len1;
    buffers = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    err = res = null;
    if (buffers.length < 2) {
      throw new Error("need 2 or more buffers");
    }
    l = buffers[0].length;
    res = new Buffer((function() {
      var _i, _results;
      _results = [];
      for (_i = 0; 0 <= l ? _i < l : _i > l; 0 <= l ? _i++ : _i--) {
        _results.push(0);
      }
      return _results;
    })());
    for (i = _i = 0, _len = buffers.length; _i < _len; i = ++_i) {
      b = buffers[i];
      if (b.length !== l) {
        err = new Error("Buffer " + i + " is length " + b.length + " != " + l);
        break;
      }
      for (j = _j = 0, _len1 = b.length; _j < _len1; j = ++_j) {
        c = b[j];
        res[j] ^= c;
      }
    }
    return res;
  };

}).call(this);
